Make sure pipeline fail when tests are failing  (#4)
* Test the test

* Update Makefile

* Update Makefile

* Update test.yml

* Update test.yml

* Update TestNumber9.c

* Update test.yml

* Update TestNumber9.c

* Update test.yml

* Update test.yml

* Update TestNumber9.c

* Update test.yml

* Update TestNumber9.c

* Update TestNumber9.c

* Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -13,4 +13,17 @@ jobs:
     - name: Check out repository
       uses: actions/checkout@v4
 
-    - run: make test       
+    - run: make test
+    - name: Check results and set pipeline status
+      run: |
+        # Directory to check
+        DIR_TO_CHECK="build/results"
+
+        # Search for files containing the text "FAIL"
+        if grep -rq "FAIL" "$DIR_TO_CHECK"; then
+          echo "A file contains the text 'FAIL'."
+          exit 1
+        else
+          echo "No files with the text 'FAIL' found."
+          exit 0
+        fi
